import type { Locale } from "./locale";

const english: Record<string, string> = {
  "Paket ve fiyatlandırma": "Plans and pricing",
  "Veri aktarımı": "Data migration",
  "Kullanıcı yetkileri": "User permissions",
  "Kurulum": "Setup",
  "Diğer": "Other",
  "1–5 araç": "1–5 vehicles",
  "6–10 araç": "6–10 vehicles",
  "11–25 araç": "11–25 vehicles",
  "26–50 araç": "26–50 vehicles",
  "51–100 araç": "51–100 vehicles",
  "100+ araç": "100+ vehicles",
  "Belirtmek istemiyorum": "Prefer not to say",
  "Lütfen güvenlik doğrulamasını tamamlayın.": "Please complete the security check.",
  "Çok sayıda talep gönderdiniz. Lütfen daha sonra tekrar deneyin.": "Too many requests. Please try again later.",
  "Mesaj gönderilemedi. Lütfen bilgilerinizi kontrol edip tekrar deneyin.": "Your message could not be sent. Please check your details and try again.",
  "Mesajınızı aldık. En kısa sürede sizinle iletişime geçeceğiz.": "We have received your message. We will get back to you as soon as possible.",
  "Mesaj gönderilemedi. Bağlantınızı kontrol edip tekrar deneyin.": "Your message could not be sent. Check your connection and try again.",
  "Bize yazın": "Contact us",
  "İhtiyacınızı kısaca anlatın": "Tell us what you need",
  "Formu gönderin; talebiniz doğrudan Rent Okey ekibine iletilsin.": "Send your request directly to the Rent Okey team.",
  "Görüşme konusu": "Topic",
  "Ad Soyad": "Full name",
  "Ad soyad": "Full name",
  "Adınız Soyadınız": "Your full name",
  "E-posta": "Email",
  "ornek@sirket.com": "you@company.com",
  "Firma": "Company (optional)",
  "Firma adı": "Company name",
  "Telefon": "Phone (optional)",
  "Filo büyüklüğü": "Fleet size (optional)",
  "Mesajınız": "Your message",
  "Size nasıl yardımcı olabiliriz?": "How can we help?",
  "Gönderiliyor…": "Sending…",
  "Mesajı gönder": "Send message",
  "Bilgileriniz yalnızca talebinizi yanıtlamak için kullanılır.": "Your details are used to respond to your request.",
  "Formu gönderdiğinizde bilgileriniz talebinizi yanıtlamak amacıyla işlenir. Ayrıntılar için": "Your information is processed to respond to your request. Read our",
  "Gizlilik ve KVKK metnini": "Privacy Policy",
  "inceleyebilirsiniz.": "for more information.",
  "Hesabınız oluşturuldu": "Account created",
  "E-posta adresinizi doğrulayın.": "Verify your email address.",
  "üzerinden gönderdiğimiz doğrulama bağlantısına tıklayın. Ardından Rent Okey&apos;e giriş yaparken firma adınızı ve filo büyüklüğünüzü tanımlayabilirsiniz.": "sends your verification email. Follow the link, then sign in to Rent Okey to set up your company name and fleet size.",
  "E-posta birkaç dakika içinde görünmezse spam veya gereksiz klasörünü de kontrol edin.": "If the email does not arrive within a few minutes, check your spam or junk folder.",
  "Rent Okey girişine git": "Go to Rent Okey sign-in",
  "Farklı bir e-posta ile başvur": "Use another email address",
  "21 günlük ücretsiz deneme": "21-day free trial",
  "Hesabınızı oluşturun": "Create your account",
  "Tek adım": "One step",
  "Firma ve filo bilgilerinizi e-posta doğrulamasından sonra uygulamada tanımlayacaksınız.": "You will set up your company and fleet in the app after verifying your email.",
  "İş e-postası": "Work email",
  "ornek@firmaniz.com": "you@company.com",
  "Şifre": "Password",
  "En az 8 karakter kullanın.": "Use at least 8 characters.",
  "Güçlü bir şifre oluşturun": "Create a strong password",
  "Şifreyi gizle": "Hide password",
  "Şifreyi göster": "Show password",
  "Kullanım Şartları": "Terms of Use",
  "ve": "and",
  "Gizlilik Politikası": "Privacy Policy",
  "&apos;nı kabul ediyorum.": ".",
  "Hesap oluşturuluyor": "Creating your account",
  "Ücretsiz hesabı oluştur": "Create free account",
  "Kredi kartı ve ödeme bilgisi istenmez": "No credit card or payment details required",
  "Güvenlik doğrulaması tamamlanamadı. Lütfen sayfayı yenileyip tekrar deneyin.": "The security check failed. Please reload the page and try again.",
  "Güvenlik doğrulaması yapılandırılmadı. Lütfen daha sonra tekrar deneyin.": "The security check is unavailable. Please try again later or contact us.",
  "Güvenlik doğrulaması": "Security check"
};

export function formCopy(text: string, locale: Locale): string {
  return locale === "en" ? english[text] ?? text : text.replaceAll("&apos;", "'");
}
