import Button from "@/components/Button";
import PageHero from "@/components/PageHero";
import EnglishPilotDemo from "@/components/english/EnglishPilotDemo";
import { EnglishSection, EnglishCta } from "@/components/english/EnglishSections";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "RentOkey Pilot — Operation Plans & Smart Pricing", description: "Review vehicle assignments, preparation risks and smart pricing suggestions with RentOkey Pilot. A paid add-on that only applies the changes you approve.", path: "/en/pilot" });

export default function PilotPage() {
  return <><PageHero eyebrow="RentOkey Pilot · optional paid add-on" title="Turn operational risks into a plan you can approve." description="See the issue, review the suggested solution and its estimated impact, then decide what to apply. Smart pricing suggestions are included in Pilot." /><section className="container-page pb-16"><EnglishPilotDemo /></section><EnglishSection id="scenarios" eyebrow="What Pilot looks for" title="Five situations worth catching early."><div className="grid gap-4 sm:grid-cols-2">{[["Tight preparation windows","Cleaning or transfer time may be insufficient between a return and the next pickup."],["Missing or unsuitable assignments","A booking needs a vehicle or is assigned to the wrong class."],["Maintenance conflicts","Planned maintenance and a reservation compete for the same vehicle."],["Outstanding payments","A balance still needs attention before an upcoming handover."],["Idle vehicles","Smart pricing suggestions identify opportunities, without promising a new booking."]].map(([title,text]) => <div key={title} className="rounded-2xl border border-surface-border p-6"><h3 className="font-bold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-brand-navy/60">{text}</p></div>)}</div></EnglishSection><EnglishSection id="control" eyebrow="Your team stays in control" title="Suggestions first. Confirmation before changes."><ol className="grid gap-5 md:grid-cols-3">{["Review the issue, reason and estimated financial or operational impact.","Select the actions that fit your priorities and compare the proposed plan.","Confirm the selected changes. Unapproved suggestions do not alter your operation."].map((text,i) => <li key={text} className="rounded-2xl bg-surface-soft p-6"><span className="text-sm font-bold text-brand-green-dark">0{i+1}</span><p className="mt-3 text-sm leading-relaxed">{text}</p></li>)}</ol><p className="mt-6 text-sm text-brand-navy/60">Pilot is not included in the base subscription. Contact us for pricing and trial availability. The demo’s financial figures are illustrative gross booking values excluding VAT, not guaranteed revenue or profit.</p><div className="mt-6"><Button href="/en#contact" icon>Ask about Pilot</Button></div></EnglishSection><EnglishCta /></>;
}
